[package]
name = "novas"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.21.3"
ureq = "2.6.2"
serde = {version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
colour = "0.6.0"